### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-securing-server-client-endpoints.introduction-endpoint-security
title: Introduction to endpoint security
metadata:
  title: Introduction to endpoint security
  description: Learn about designing security solutions for server and client endpoints, including servers, mobile devices, IoT systems, and operational technology.
  ms.date: 02/07/2026
  author: ceperezb
  ms.author: ceperezb
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/1-introduction-endpoint-security.md)]