### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-applications.introduction-application-security
title: Introduction
metadata:
  title: Introduction
  description: "Introduction to the module, Design solutions for securing applications."
  ms.date: 02/10/2026
  author: ceperezb
  ms.author: ceperezb
  ms.topic: unit
durationInMinutes: 3
content: |
  [!include[](includes/1-introduction-application-security.md)]