### YamlMime:ModuleUnit
uid: learn.wwl.design-solutions-secure-applications.evaluate-application-threats-threat-modeling
title: Evaluate application threats with threat modeling
metadata:
  title: Evaluate application threats with threat modeling
  description: "SC-100 preparatory unit on this topic: evaluate application threats with threat modeling."
  ms.date: 02/10/2026
  author: ceperezb
  ms.author: ceperezb
  ms.topic: unit
durationInMinutes: 9
content: |
  [!include[](includes/4-evaluate-application-threats-threat-modeling.md)]