### YamlMime:ModuleUnit
uid: learn.wwl.manage-secure-ai-ready-infrastructure.configure-azure-rbac-infrastructure-components
title: "Configure Azure RBAC for AI infrastructure components"
metadata:
  title: "Configure Azure RBAC for AI infrastructure components"
  description: "Configure Azure RBAC for AI infrastructure components."
  ms.date: 02/02/2026
  author: wwlpublish
  ms.author: bradj
  ms.topic: unit
durationInMinutes: 13
content: |
  [!include[](includes/2-configure-azure-rbac-infrastructure-components.md)]
